### ISSUE TITLE
 Clear notifications 

### ISSUE THREAD

**Issue by weggethegamer** [CreatureSurvive/consolidation#1]
Can't clear notifications If they are from Yesterday. I have a video on it If u want.

**Comment by CreatureSurvive** [comment]
@weggethegamer Thank you for reporting, and sorry you're having issues.  I have fixed this issue in alpha 5, which will hopefully be out tomorrow.

**Comment by weggethegamer** [comment]
Thx!
The problem with alpha 5 is that the apps have a black mask around them
that i can't seem to disable.
Do u know why?
