### ISSUE TITLE
ColorBadges Incompatible

### ISSUE THREAD

**Issue by AncientPhantom** [CreatureSurvive/consolidation#4]
ColorBadges was active in the first few alphas but it has been since removed in alpha 5. Maybe you can add an option that enables ColorBadges on lock screen notifications?

**Comment by CreatureSurvive** [comment]
@AncientPhantom ColorBadges support will be added back in during the Beta Cycle, the reason it was removed is that the app selection view was rewritten from scratch to fix a number of other issues. Native badges that support theming and 3rd Party tweaks will be added in during the Beta Cycle.

**Comment by CreatureSurvive** [comment]
@AncientPhantom I Just Added ColorBadges support back in, this will be included in the next release.
