### ISSUE TITLE
[Bug] LS notification list icon disappear with large Icons

### ISSUE THREAD

**Issue by TheSolly** [CreatureSurvive/consolidation#6]
When choosing large icons on the LS, the icon for all notification list disappear.

**Comment by CreatureSurvive** [comment]
@solly84 I noticed this yesterday as well, only I was using small icons. it seemed to only happen after receiving a large number of notifications throughout the day. I will be looking into it.

**Comment by CreatureSurvive** [comment]
@solly84 I believe I've fixed this issue, we'll see how the next release goes before I close this.

**Comment by TheSolly** [comment]
@CreatureSurvive Tested this throughout the day with Alpha 6, and can confirm it doesnt exist anymore. would suggest closing it.

Thanks a lot for your effort. You are doing a great job here...

**Comment by CreatureSurvive** [comment]
@TheSolly great, thanks for the feedback. I'll go ahead and close this.
