### ISSUE TITLE
[Request] No "all apps" selection option

### ISSUE THREAD

**Issue by Rougemoot** [CreatureSurvive/consolidation#9]
I'd like to have an option to disable the "all apps" button on the left of all the apps in the selection. I hope this makes sense, and I've been looking for it in the settings of the tweak and haven't found it, but if it's there already and I missed it then I'm sorry

**Comment by sween64** [comment]
I agree. I'd like that option as well.

**Comment by CreatureSurvive** [comment]
@Rougemoot @sween64 The feature will be optional as of alpha 6.

**Comment by Rougemoot** [comment]
Awesome, many thanks.

**Comment by CreatureSurvive** [comment]
@Rougemoot @sween64 I just added this in, it will be included in the next release.
